apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: betakronan.se
build:
  artifacts:
  - image: iteam1337/betakronan-landingpage
deploy:
  kubectl:
    manifests:
    - k8s/*.yaml
    flags:
      global:
        - --namespace=betakronan