apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: betakronan-ingress
  namespace: betakronan
  annotations:
    kubernetes.io/ingress.class: "public"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - betakronan.se
    secretName: betakronan-prod-tls
  rules:
  - host: betakronan.se
    http:
      paths:
      - backend:
          serviceName: betakronan-landingpage
          servicePort: 80